# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ $default-branch ]
  pull_request:
    branches: []
  workflow_dispatch:
    inputs:
      logLevel:
        required: false
        default: 'debug'

permissions:
  contents: read

jobs:
  build:
    name: Continuous Integration
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v4
      with:
        version: "0.5.9"

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version-file: ".python-version"

    - name: Install Python package dependencies for this app
      run: uv sync --all-extras --dev

    - name: Lint
      run: uv run ruff check --output-format=github .

    - name: Unit tests
      run: uv run pytest -s
